# Generated by Django 3.0.4 on 2020-03-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=26)),
                ('fingso', models.DateTimeField(blank=True, null=True)),
                ('descrip', models.CharField(max_length=60)),
                ('umedida', models.CharField(max_length=5)),
                ('distb1', models.CharField(max_length=30)),
                ('costo1', models.FloatField(default=0.0)),
                ('cantm1', models.FloatField(default=0.0)),
                ('factu1', models.DateTimeField(blank=True, null=True)),
                ('distb2', models.CharField(blank=True, max_length=30, null=True)),
                ('costo2', models.FloatField(blank=True, default=0.0, null=True)),
                ('cantm2', models.FloatField(blank=True, default=0.0, null=True)),
                ('factu2', models.DateTimeField(blank=True, null=True)),
                ('distb3', models.CharField(blank=True, max_length=30, null=True)),
                ('costo3', models.FloatField(blank=True, default=0.0, null=True)),
                ('cantm3', models.FloatField(blank=True, default=0.0, null=True)),
                ('factu3', models.DateTimeField(blank=True, null=True)),
                ('distb4', models.CharField(blank=True, max_length=30, null=True)),
                ('costo4', models.FloatField(blank=True, default=0.0, null=True)),
                ('cantm4', models.FloatField(blank=True, default=0.0, null=True)),
                ('factu4', models.DateTimeField(blank=True, null=True)),
                ('distb5', models.CharField(blank=True, max_length=30, null=True)),
                ('costo5', models.FloatField(blank=True, default=0.0, null=True)),
                ('cantm5', models.FloatField(blank=True, default=0.0, null=True)),
                ('factu5', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
