# Generated by Django 3.0.4 on 2020-03-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='insumos',
            new_name='InsumosM',
        ),
    ]
