# Generated by Django 3.0.4 on 2020-04-02 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0003_auto_20200401_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumosm',
            name='ctmax',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='ctmin',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='ctprom',
        ),
    ]
