# Generated by Django 3.0.4 on 2020-04-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0005_auto_20200405_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumosm',
            old_name='cantm1',
            new_name='cantd',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='cantm2',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='cantm3',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='cantm4',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='cantm5',
        ),
    ]
