# Generated by Django 3.0.4 on 2020-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0008_auto_20200503_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumosm',
            name='tipo',
            field=models.CharField(choices=[('1', 'MATERIAL'), ('2', 'PERSONAL'), ('3', 'MAQyHERR'), ('4', 'SERVICIO'), ('5', 'INGREDIENTE')], default='5', max_length=6),
        ),
    ]
