# Generated by Django 3.0.4 on 2020-05-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0009_insumosm_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumosm',
            name='tipo',
            field=models.CharField(max_length=14),
        ),
    ]
