# Generated by Django 3.0.4 on 2020-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0010_auto_20200505_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumosm',
            name='tipo',
            field=models.CharField(choices=[('1', 'MATERIAL'), ('2', 'PERSONAL'), ('3', 'MAQyHERR'), ('4', 'SERVICIO'), ('5', 'INGREDIENTE')], default='5', max_length=14),
        ),
    ]
