# Generated by Django 3.0.4 on 2020-05-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0011_auto_20200505_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumosm',
            name='tipo',
            field=models.CharField(choices=[('MAT', 'MATERIAL'), ('PER', 'PERSONAL'), ('MYH', 'MAQyHERR'), ('SER', 'SERVICIO'), ('ING', 'INGREDIENTE')], default='5', max_length=14),
        ),
    ]
