# Generated by Django 3.0.4 on 2020-05-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0013_auto_20200519_0241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtrosCostosM',
        ),
    ]
