# Generated by Django 3.0.4 on 2020-05-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0014_delete_otroscostosm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosAdicionalesM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprod', models.IntegerField()),
                ('descrip', models.CharField(blank=True, max_length=20, null=True)),
                ('umedida', models.CharField(max_length=5)),
                ('cumedida', models.FloatField(blank=True, default=0.0, null=True)),
                ('cantidad', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtrosCostosM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprd', models.IntegerField()),
                ('electricidad', models.FloatField(blank=True, default=0.0, null=True)),
                ('transporte', models.FloatField(blank=True, default=0.0, null=True)),
                ('agua', models.FloatField(blank=True, default=0.0, null=True)),
                ('utilidades', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
