# Generated by Django 3.0.4 on 2020-05-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0015_costosadicionalesm_otroscostosm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostosAdicionalesM',
        ),
        migrations.DeleteModel(
            name='OtrosCostosM',
        ),
    ]
