# Generated by Django 3.0.4 on 2020-05-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0016_auto_20200522_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumosm',
            name='inven',
            field=models.FloatField(default=0.0),
        ),
    ]
