# Generated by Django 3.0.4 on 2020-06-14 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0017_insumosm_inven'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumosm',
            name='fingso',
        ),
    ]
