# Generated by Django 3.0.4 on 2020-07-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0019_auto_20200708_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idinsm', models.IntegerField()),
                ('costo', models.FloatField()),
                ('cantd', models.FloatField()),
                ('nfactu', models.IntegerField()),
                ('fhcomp', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='Facturas/')),
            ],
        ),
    ]
