# Generated by Django 3.0.4 on 2020-07-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0020_comprasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasm',
            name='archivo',
            field=models.FileField(default='', upload_to='Facturas/'),
        ),
    ]
