# Generated by Django 3.0.4 on 2020-08-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0021_auto_20200730_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasm',
            name='archivo',
            field=models.FileField(upload_to='Facturas/'),
        ),
        migrations.AlterField(
            model_name='comprasm',
            name='fhcomp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
