# Generated by Django 3.0.4 on 2020-08-02 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0022_auto_20200801_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasm',
            name='fhcomp',
            field=models.DateField(default=datetime.date(2020, 8, 1)),
            preserve_default=False,
        ),
    ]
