# Generated by Django 3.0.4 on 2020-08-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0023_auto_20200801_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0e0', max_length=24)),
                ('numero', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0.0)),
                ('fhfactu', models.DateField()),
            ],
        ),
    ]
