# Generated by Django 3.0.4 on 2020-08-03 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0024_facturasm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasm',
            name='archivo',
        ),
        migrations.AddField(
            model_name='facturasm',
            name='archivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='Facturas/'),
            preserve_default=False,
        ),
    ]
