# Generated by Django 3.0.4 on 2020-08-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0025_auto_20200802_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasm',
            name='umedida',
            field=models.CharField(default='UND', max_length=5),
            preserve_default=False,
        ),
    ]
