# Generated by Django 3.0.4 on 2020-08-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0026_comprasm_umedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasm',
            name='emisor',
            field=models.CharField(default='local', max_length=24),
        ),
    ]
