# Generated by Django 3.0.4 on 2020-09-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0027_facturasm_emisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasm',
            name='archivo',
            field=models.FileField(default='', upload_to='facturas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturasm',
            name='codigo',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='facturasm',
            name='emisor',
            field=models.CharField(default='', max_length=24),
        ),
    ]
