# Generated by Django 3.0.4 on 2020-09-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0028_auto_20200902_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasm',
            name='archivo',
        ),
        migrations.AlterField(
            model_name='facturasm',
            name='archivo',
            field=models.FileField(upload_to='facturas/'),
        ),
    ]
