# Generated by Django 3.0.4 on 2020-10-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0029_auto_20200902_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasm',
            old_name='nfactu',
            new_name='idfactu',
        ),
    ]
