# Generated by Django 3.0.4 on 2020-10-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0030_auto_20201005_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasm',
            name='trasnp',
            field=models.FloatField(default=0.0),
        ),
    ]
