# Generated by Django 3.0.4 on 2020-10-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0031_facturasm_trasnp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturasm',
            old_name='trasnp',
            new_name='transp',
        ),
    ]
