# Generated by Django 3.0.4 on 2020-10-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0032_auto_20201005_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasm',
            name='costo',
        ),
        migrations.AddField(
            model_name='comprasm',
            name='costop',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comprasm',
            name='costot',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='comprasm',
            name='cantd',
            field=models.FloatField(default=0.0),
        ),
    ]
