# Generated by Django 3.0.4 on 2020-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0033_auto_20201011_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumosm',
            old_name='costo1',
            new_name='costop',
        ),
        migrations.AddField(
            model_name='insumosm',
            name='costot',
            field=models.FloatField(default=0.0),
        ),
    ]
