# Generated by Django 3.0.4 on 2020-10-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0034_auto_20201011_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumosm',
            name='costo2',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='costo3',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='costo4',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='costo5',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='distb2',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='distb3',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='distb4',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='distb5',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='factu1',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='factu2',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='factu3',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='factu4',
        ),
        migrations.RemoveField(
            model_name='insumosm',
            name='factu5',
        ),
    ]
