# Generated by Django 3.0.4 on 2020-10-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0035_auto_20201011_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumosm',
            name='distb1',
        ),
    ]
