# Generated by Django 3.0.4 on 2020-10-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0036_remove_insumosm_distb1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumosm',
            old_name='cantd',
            new_name='cumedida',
        ),
    ]
