# Generated by Django 3.0.4 on 2020-10-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0037_auto_20201013_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumosm',
            old_name='cumedida',
            new_name='cantd',
        ),
    ]
