# Generated by Django 3.0.4 on 2020-11-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0039_insumosm_cumedcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasm',
            name='observ',
            field=models.CharField(default='', max_length=500),
        ),
    ]
