# Generated by Django 3.0.4 on 2020-05-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosDetallesM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpart', models.IntegerField()),
                ('unidad', models.IntegerField()),
                ('cantid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductosM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb', models.CharField(max_length=20)),
                ('codp', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=1000)),
                ('unid', models.IntegerField()),
            ],
        ),
    ]
