# Generated by Django 3.0.4 on 2020-06-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosm',
            old_name='costo',
            new_name='costo1',
        ),
    ]
