# Generated by Django 3.0.4 on 2020-05-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_auto_20200503_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosdetallesm',
            old_name='cantid',
            new_name='cant',
        ),
        migrations.RenameField(
            model_name='productosdetallesm',
            old_name='unidad',
            new_name='idprd',
        ),
        migrations.AddField(
            model_name='productosdetallesm',
            name='unid',
            field=models.IntegerField(default=(0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productosm',
            name='unid',
            field=models.CharField(max_length=10),
        ),
    ]
