# Generated by Django 3.0.4 on 2020-05-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0003_auto_20200504_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosdetallesm',
            name='unid',
            field=models.CharField(max_length=10),
        ),
    ]
