# Generated by Django 3.0.4 on 2020-05-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_auto_20200504_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosdetallesm',
            name='unid',
        ),
    ]
