# Generated by Django 3.0.4 on 2020-06-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_auto_20200624_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendidosM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprod', models.IntegerField()),
                ('idclie', models.IntegerField()),
                ('cant', models.FloatField()),
                ('costo', models.FloatField()),
                ('mobra', models.FloatField()),
                ('insm', models.FloatField()),
                ('mate', models.FloatField()),
                ('cadln', models.FloatField()),
                ('utlds', models.FloatField()),
                ('obsrv', models.CharField(max_length=1000)),
                ('direc', models.CharField(max_length=500)),
                ('centr', models.FloatField()),
                ('fhacd', models.DateTimeField(auto_now_add=True)),
                ('fhentr', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productosm',
            name='fhentr',
        ),
    ]
