# Generated by Django 3.0.4 on 2020-05-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0005_remove_productosdetallesm_unid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosdetallesm',
            name='unid',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
