# Generated by Django 3.0.4 on 2020-06-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0005_auto_20200625_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendidosM',
            new_name='VentasM',
        ),
    ]
