# Generated by Django 3.0.4 on 2020-05-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0006_productosdetallesm_unid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquiyHerraM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idism', models.CharField(max_length=16)),
                ('idprd', models.CharField(max_length=60)),
                ('unid', models.CharField(max_length=4)),
                ('cant', models.FloatField()),
            ],
        ),
    ]
