# Generated by Django 3.0.4 on 2020-06-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0007_auto_20200629_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasm',
            name='direc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ventasm',
            name='obsrv',
            field=models.CharField(default='', max_length=50),
        ),
    ]
