# Generated by Django 3.0.4 on 2020-05-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0007_maquiyherram'),
    ]

    operations = [
        migrations.CreateModel(
            name='CstsAdnlsM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcstanls', models.IntegerField()),
                ('idprod', models.IntegerField()),
                ('cant', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='maquiyherram',
            name='idism',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maquiyherram',
            name='idprd',
            field=models.IntegerField(),
        ),
    ]
