# Generated by Django 3.0.4 on 2020-07-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0008_auto_20200629_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosm',
            old_name='cadln',
            new_name='serv',
        ),
        migrations.RenameField(
            model_name='ventasm',
            old_name='cadln',
            new_name='serv',
        ),
        migrations.AlterField(
            model_name='ventasm',
            name='obsrv',
            field=models.CharField(max_length=500),
        ),
    ]
