# Generated by Django 3.0.4 on 2020-07-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0009_auto_20200707_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosm',
            name='pinsm',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='productosm',
            name='pmate',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='productosm',
            name='pmobra',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='productosm',
            name='pserv',
            field=models.FloatField(default=30.0),
        ),
    ]
