# Generated by Django 3.0.4 on 2020-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0009_cstsadnlsm_cumedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstsadnlsm',
            name='cant',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cstsadnlsm',
            name='cumedida',
            field=models.FloatField(default=1.0),
        ),
    ]
