# Generated by Django 3.0.4 on 2020-07-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0010_auto_20200712_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosm',
            name='insm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productosm',
            name='mate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productosm',
            name='mobra',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productosm',
            name='serv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productosm',
            name='utlds',
            field=models.FloatField(default=0.0),
        ),
    ]
