# Generated by Django 3.0.4 on 2020-05-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0011_auto_20200526_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cstsadnlsm',
            old_name='idprod',
            new_name='idprd',
        ),
    ]
