# Generated by Django 3.0.4 on 2020-07-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0011_auto_20200712_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasm',
            name='centr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ventasm',
            name='direc',
            field=models.CharField(default='Retiro en tienda', max_length=100),
        ),
    ]
