# Generated by Django 3.0.4 on 2020-07-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0013_manodeobram_materialesm_partidasm_serviciosm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VentasM',
        ),
    ]
