# Generated by Django 3.0.4 on 2020-05-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0014_auto_20200526_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosm',
            name='costo',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
