# Generated by Django 3.0.4 on 2020-07-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0014_delete_ventasm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartidasM',
            new_name='PartidasPRDM',
        ),
    ]
