# Generated by Django 3.0.4 on 2020-05-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0015_productosm_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosm',
            name='costo',
            field=models.FloatField(default=1.0),
        ),
    ]
