# Generated by Django 3.0.4 on 2020-07-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0015_auto_20200718_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManoDeObraM',
            new_name='PersonalM',
        ),
        migrations.RenameField(
            model_name='personalm',
            old_name='idmobra',
            new_name='idper',
        ),
    ]
