# Generated by Django 3.0.4 on 2020-07-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0016_auto_20200718_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalm',
            old_name='idper',
            new_name='idpers',
        ),
        migrations.RenameField(
            model_name='productosm',
            old_name='mobra',
            new_name='pers',
        ),
    ]
