# Generated by Django 3.0.4 on 2020-07-19 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0017_auto_20200718_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosm',
            old_name='pmobra',
            new_name='ppers',
        ),
    ]
