# Generated by Django 3.0.4 on 2020-07-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0018_auto_20200718_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquiyherram',
            name='unid',
            field=models.CharField(max_length=10),
        ),
    ]
