# Generated by Django 3.0.4 on 2020-07-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0018_auto_20200718_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CstsAdnlsM',
        ),
        migrations.DeleteModel(
            name='MaquiyHerraM',
        ),
    ]
