# Generated by Django 3.0.4 on 2020-09-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0020_imagenesprd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenesPRD',
        ),
    ]
