# Generated by Django 3.0.4 on 2020-09-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0021_delete_imagenesprd'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosm',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productosm',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productosm',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
