# Generated by Django 3.0.4 on 2020-09-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0023_auto_20200902_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprod', models.IntegerField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='facturas/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='facturas/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='facturas/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='facturas/')),
            ],
        ),
        migrations.RemoveField(
            model_name='productosm',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='productosm',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='productosm',
            name='imagen3',
        ),
    ]
