# Generated by Django 3.0.4 on 2020-09-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0027_auto_20200919_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesm',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagenesm',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagenesm',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagenesm',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
