# Generated by Django 3.0.4 on 2021-02-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0028_auto_20200919_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeDatos_Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpart', models.IntegerField()),
                ('unid', models.CharField(max_length=10)),
                ('cant', models.FloatField()),
            ],
        ),
    ]
