# Generated by Django 3.0.4 on 2020-05-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostosAdicionalesM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprod', models.IntegerField()),
                ('descrip', models.CharField(blank=True, max_length=20, null=True)),
                ('umedida', models.CharField(max_length=5)),
                ('cumedida', models.FloatField(default=0.0)),
                ('cantidad', models.FloatField(default=0.0)),
            ],
        ),
    ]
