# Generated by Django 3.0.4 on 2020-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosDescripcionM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=24, null=True)),
                ('umedida', models.CharField(blank=True, max_length=12, null=True)),
                ('cumedida', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='costosadicionalesm',
            name='descrip',
        ),
        migrations.RemoveField(
            model_name='costosadicionalesm',
            name='umedida',
        ),
        migrations.AddField(
            model_name='costosadicionalesm',
            name='idcstd',
            field=models.IntegerField(default=0),
        ),
    ]
