# Generated by Django 3.0.4 on 2020-05-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20200522_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostosAdicionalesM',
        ),
    ]
