# Generated by Django 3.0.4 on 2020-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_delete_costosadicionalesm'),
    ]

    operations = [
        migrations.AddField(
            model_name='costosdescripcionm',
            name='referencia',
            field=models.CharField(blank=True, default='TOTAL', max_length=10, null=True),
        ),
    ]
