# Generated by Django 3.0.4 on 2020-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_costosdescripcionm_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosdescripcionm',
            name='referencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
