# Generated by Django 3.0.4 on 2020-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0005_auto_20200531_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosdescripcionm',
            name='referencia',
            field=models.CharField(choices=[('TINS', 'INSUMOS'), ('TMAT', 'MATERIALES'), ('TIMA', 'INSUMOS+MATERIALES')], default='INSUMOS+MATERIALES', max_length=10),
        ),
    ]
