# Generated by Django 3.0.4 on 2020-06-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0007_auto_20200531_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosdescripcionm',
            name='umedida',
            field=models.CharField(choices=[('%', 'PORCENTAJE'), ('Kwh', 'KILOVATIO-HORA'), ('M3', 'METROS CUBICOS'), ('Lts', 'LITROS'), ('Kgr', 'KILOGRAMOS'), ('Gr', 'Gramos'), ('Mts', 'METROS'), ('Km', 'KILOMETROS'), ('Und', 'UNIDAD'), ('HH', 'HORAS-HOMBRE')], default='%', max_length=12),
        ),
    ]
