# Generated by Django 3.0.4 on 2020-07-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0010_costosdescripcionm_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosdescripcionm',
            name='tipo',
            field=models.CharField(choices=[('SERV', 'SERVICIO'), ('MOBR', 'INSUMO'), ('MYHR', 'MAQUINA y HERRAMIENTA'), ('MOBR', 'MANO DE OBRA')], default='SERVICIO', max_length=4),
        ),
        migrations.AlterField(
            model_name='costosdescripcionm',
            name='umedida',
            field=models.CharField(choices=[('%', 'PORCENTAJE'), ('Kwh', 'KILOVATIO-HORA'), ('M3', 'METROS CUBICOS'), ('Lts', 'LITROS'), ('Kgr', 'KILOGRAMOS'), ('Gr', 'Gramos'), ('Mts', 'METROS'), ('Km', 'KILOMETROS'), ('Und', 'UNIDAD'), ('HH', 'HORAS-HOMBRE'), ('MES', 'MENUSAL'), ('DIA', 'DIARIO'), ('HRS', 'HORAS')], default='%', max_length=12),
        ),
    ]
