# Generated by Django 3.0.4 on 2020-07-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0011_auto_20200708_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=24, null=True)),
                ('porcentaje', models.FloatField(default=30.0)),
            ],
        ),
        migrations.AlterField(
            model_name='costosdescripcionm',
            name='tipo',
            field=models.CharField(choices=[('SERV', 'SERVICIO'), ('INSM', 'INSUMO'), ('MYHR', 'MAQUINA y HERRAMIENTA'), ('PER', 'PERSONAL')], default='SERVICIO', max_length=4),
        ),
    ]
