# Generated by Django 3.0.4 on 2020-07-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0012_auto_20200709_0232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilidades',
            new_name='UtilidadesM',
        ),
    ]
