# Generated by Django 3.0.4 on 2020-07-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0013_auto_20200709_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilidadesDetallesM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprod', models.IntegerField()),
                ('idutil', models.IntegerField()),
                ('porcentaje', models.FloatField(default=0.0)),
                ('valor', models.FloatField(default=0.0)),
            ],
        ),
    ]
