# Generated by Django 3.0.4 on 2020-07-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0008_auto_20200604_0022'),
        ('conf', '0014_utilidadesdetallesm'),
    ]

    operations = [
    ]
