# Generated by Django 3.0.4 on 2020-07-20 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200622_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferidosM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='ASL', max_length=40)),
                ('telefono', models.CharField(max_length=15)),
                ('fhreg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientesm',
            name='fhreg',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientesm',
            name='idrefe',
            field=models.IntegerField(default=1),
        ),
    ]
