# Generated by Django 3.0.4 on 2020-10-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clientesm_fhaniver'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesm',
            name='correo',
            field=models.EmailField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
