# Generated by Django 3.0.4 on 2020-03-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproy', models.IntegerField()),
                ('tipo', models.CharField(choices=[('PLNO', 'Plano'), ('EETT', 'Especificaciones Técnicas'), ('ESUE', 'Estudio de Suelo'), ('BAGE', 'Bases Administrativas Generales'), ('BAES', 'Bases Administrativas Especficas'), ('OTRA', 'Documento de Especificado')], max_length=4)),
                ('descrip1', models.CharField(blank=True, max_length=60, null=True)),
                ('archivo1', models.FileField(blank=True, null=True, upload_to='Descargas/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=None, default='2020-03-31 03:35:30', null=None)),
                ('cliente', models.CharField(max_length=20)),
                ('proyecto', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='CostoPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproy', models.IntegerField()),
                ('item', models.CharField(max_length=6)),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallePartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpart', models.IntegerField()),
                ('idtipo', models.IntegerField()),
                ('codi', models.CharField(max_length=16)),
                ('cant', models.FloatField()),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MaquiyHerra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=16)),
                ('desc', models.CharField(max_length=60)),
                ('unid', models.CharField(max_length=4)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=16)),
                ('desc', models.CharField(max_length=60)),
                ('unid', models.CharField(max_length=4)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproy', models.IntegerField()),
                ('item', models.CharField(max_length=6)),
                ('part', models.CharField(blank=None, max_length=100, null=None)),
                ('desc', models.CharField(max_length=1000)),
                ('unid', models.CharField(max_length=4)),
                ('cant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=4)),
                ('espc', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=60)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
