# Generated by Django 3.0.4 on 2020-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0002_auto_20200331_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaDetallesM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codp', models.IntegerField()),
                ('codm', models.IntegerField()),
                ('cant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PartidasM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codp', models.IntegerField()),
                ('nomb', models.CharField(blank=None, max_length=100, null=None)),
                ('desc', models.CharField(max_length=1000)),
                ('unid', models.CharField(max_length=4)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-03-31 15:16:38', null=None),
        ),
    ]
