# Generated by Django 3.0.4 on 2020-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0003_auto_20200331_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-03-31 15:47:29', null=None),
        ),
    ]
