# Generated by Django 3.0.4 on 2020-04-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0004_auto_20200331_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-01 19:54:18', null=None),
        ),
    ]
