# Generated by Django 3.0.4 on 2020-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0005_auto_20200401_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-01 19:55:00', null=None),
        ),
    ]
