# Generated by Django 3.0.4 on 2020-04-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0006_auto_20200401_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidadetallesm',
            old_name='codm',
            new_name='codi',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-01 21:22:43', null=None),
        ),
    ]
