# Generated by Django 3.0.4 on 2020-04-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0007_auto_20200401_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-02 01:47:18', null=None),
        ),
    ]
