# Generated by Django 3.0.4 on 2020-04-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0008_auto_20200402_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-05 02:51:32', null=None),
        ),
    ]
