# Generated by Django 3.0.4 on 2020-04-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0009_auto_20200405_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-05 03:21:25', null=None),
        ),
    ]
