# Generated by Django 3.0.4 on 2020-04-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0015_auto_20200411_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-11 00:07:56', null=None),
        ),
        migrations.AlterField(
            model_name='partidadetallesm',
            name='codi',
            field=models.IntegerField(blank=None, null=None),
        ),
        migrations.AlterField(
            model_name='partidadetallesm',
            name='codp',
            field=models.IntegerField(blank=None, null=None),
        ),
    ]
