# Generated by Django 3.0.4 on 2020-04-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0016_auto_20200411_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-12 22:36:27', null=None),
        ),
    ]
