# Generated by Django 3.0.4 on 2020-04-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0017_auto_20200412_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-12 22:39:27', null=None),
        ),
    ]
