# Generated by Django 3.0.4 on 2020-04-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0019_auto_20200424_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-24 21:49:44', null=None),
        ),
    ]
