# Generated by Django 3.0.4 on 2020-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0021_auto_20200429_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-04-29 17:16:35', null=None),
        ),
        migrations.AlterField(
            model_name='partidadetallesm',
            name='codi',
            field=models.IntegerField(blank=None, null=None),
        ),
    ]
