# Generated by Django 3.0.4 on 2020-05-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0022_auto_20200429_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-03 13:51:04', null=None),
        ),
    ]
