# Generated by Django 3.0.4 on 2020-05-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0025_auto_20200503_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-03 16:52:38', null=None),
        ),
    ]
