# Generated by Django 3.0.4 on 2020-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0026_auto_20200503_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-03 17:13:39', null=None),
        ),
    ]
