# Generated by Django 3.0.4 on 2020-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0034_auto_20200504_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-05 12:45:08', null=None),
        ),
    ]
