# Generated by Django 3.0.4 on 2020-05-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0036_auto_20200505_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-05 15:44:38', null=None),
        ),
    ]
