# Generated by Django 3.0.4 on 2020-05-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0039_auto_20200505_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaquiyHerra',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-05 23:25:14', null=None),
        ),
    ]
