# Generated by Django 3.0.4 on 2020-05-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0040_auto_20200505_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-19 02:41:30', null=None),
        ),
    ]
