# Generated by Django 3.0.4 on 2020-05-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0041_auto_20200519_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-19 02:58:31', null=None),
        ),
    ]
