# Generated by Django 3.0.4 on 2020-05-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0043_auto_20200520_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-22 19:23:33', null=None),
        ),
    ]
