# Generated by Django 3.0.4 on 2020-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0044_auto_20200522_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-22 19:52:23', null=None),
        ),
    ]
