# Generated by Django 3.0.4 on 2020-05-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0046_auto_20200524_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-24 05:07:41', null=None),
        ),
    ]
