# Generated by Django 3.0.4 on 2020-05-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0048_auto_20200524_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-24 17:21:05', null=None),
        ),
    ]
