# Generated by Django 3.0.4 on 2020-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0049_auto_20200524_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-24 17:22:55', null=None),
        ),
    ]
