# Generated by Django 3.0.4 on 2020-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0052_auto_20200526_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-26 16:23:24', null=None),
        ),
    ]
