# Generated by Django 3.0.4 on 2020-05-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0053_auto_20200526_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-26 16:24:36', null=None),
        ),
    ]
