# Generated by Django 3.0.4 on 2020-05-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0055_auto_20200526_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-27 00:23:10', null=None),
        ),
        migrations.AlterField(
            model_name='partidadetallesm',
            name='codi',
            field=models.IntegerField(),
        ),
    ]
