# Generated by Django 3.0.4 on 2020-05-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0056_auto_20200527_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidadetallesm',
            old_name='codp',
            new_name='idpart',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-27 00:26:36', null=None),
        ),
    ]
