# Generated by Django 3.0.4 on 2020-05-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0057_auto_20200527_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidadetallesm',
            old_name='codi',
            new_name='idism',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-27 00:35:57', null=None),
        ),
    ]
