# Generated by Django 3.0.4 on 2020-05-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0058_auto_20200527_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-28 21:41:42', null=None),
        ),
    ]
