# Generated by Django 3.0.4 on 2020-05-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0059_auto_20200528_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-28 21:46:23', null=None),
        ),
    ]
