# Generated by Django 3.0.4 on 2020-05-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0060_auto_20200530_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-30 04:09:34', null=None),
        ),
    ]
