# Generated by Django 3.0.4 on 2020-05-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0061_auto_20200530_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-30 04:11:42', null=None),
        ),
    ]
