# Generated by Django 3.0.4 on 2020-05-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0062_auto_20200530_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-31 03:46:36', null=None),
        ),
    ]
