# Generated by Django 3.0.4 on 2020-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0063_auto_20200531_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-31 13:06:48', null=None),
        ),
    ]
