# Generated by Django 3.0.4 on 2020-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0065_auto_20200531_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-31 13:41:35', null=None),
        ),
    ]
