# Generated by Django 3.0.4 on 2020-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0067_auto_20200531_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-05-31 14:34:17', null=None),
        ),
    ]
