# Generated by Django 3.0.4 on 2020-06-04 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0062_auto_20200528_2201'),
        ('partida', '0068_auto_20200531_1434'),
    ]

    operations = [
    ]
