# Generated by Django 3.0.4 on 2020-06-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0069_auto_20200614_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-06-18 03:28:58', null=None),
        ),
    ]
