# Generated by Django 3.0.4 on 2020-06-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0069_merge_20200604_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-06-04 00:22:58', null=None),
        ),
    ]
