# Generated by Django 3.0.4 on 2020-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0071_auto_20200618_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-06-18 14:24:48', null=None),
        ),
    ]
