# Generated by Django 3.0.4 on 2020-06-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0076_auto_20200622_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-06-22 14:13:08', null=None),
        ),
    ]
