# Generated by Django 3.0.4 on 2020-06-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0078_auto_20200622_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-06-24 23:34:55', null=None),
        ),
    ]
