# Generated by Django 3.0.4 on 2020-06-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0080_auto_20200625_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-06-25 04:45:29', null=None),
        ),
    ]
