# Generated by Django 3.0.4 on 2020-06-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0081_auto_20200625_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-06-25 23:12:59', null=None),
        ),
    ]
