# Generated by Django 3.0.4 on 2020-06-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0082_auto_20200625_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-06-26 02:52:06', null=None),
        ),
    ]
