# Generated by Django 3.0.4 on 2020-06-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0083_auto_20200626_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-06-29 01:19:17', null=None),
        ),
    ]
