# Generated by Django 3.0.4 on 2020-07-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0085_auto_20200629_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-07 04:08:24', null=None),
        ),
    ]
