# Generated by Django 3.0.4 on 2020-07-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0087_auto_20200707_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-08 02:57:10', null=None),
        ),
    ]
