# Generated by Django 3.0.4 on 2020-07-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0088_auto_20200708_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-09 02:32:56', null=None),
        ),
    ]
