# Generated by Django 3.0.4 on 2020-07-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0089_auto_20200709_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-09 02:42:06', null=None),
        ),
    ]
