# Generated by Django 3.0.4 on 2020-07-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0092_auto_20200711_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-12 01:56:07', null=None),
        ),
    ]
