# Generated by Django 3.0.4 on 2020-07-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0093_auto_20200712_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-12 02:03:13', null=None),
        ),
    ]
