# Generated by Django 3.0.4 on 2020-07-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0097_auto_20200718_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-18 15:33:12', null=None),
        ),
    ]
