# Generated by Django 3.0.4 on 2020-07-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0099_auto_20200718_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-18 19:40:44', null=None),
        ),
    ]
