# Generated by Django 3.0.4 on 2020-07-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0100_auto_20200718_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-18 19:54:29', null=None),
        ),
    ]
