# Generated by Django 3.0.4 on 2020-07-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0106_auto_20200718_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-19 21:47:06', null=None),
        ),
    ]
