# Generated by Django 3.0.4 on 2020-07-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0108_auto_20200720_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-20 13:34:24', null=None),
        ),
    ]
