# Generated by Django 3.0.4 on 2020-07-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0110_auto_20200720_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-20 23:26:15', null=None),
        ),
    ]
