# Generated by Django 3.0.4 on 2020-07-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0114_auto_20200721_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-21 16:42:10', null=None),
        ),
    ]
