# Generated by Django 3.0.4 on 2020-07-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0117_auto_20200721_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-21 23:00:44', null=None),
        ),
    ]
