# Generated by Django 3.0.4 on 2020-07-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0070_auto_20200604_0022'),
        ('partida', '0118_auto_20200721_2300'),
    ]

    operations = [
    ]
