# Generated by Django 3.0.4 on 2020-07-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0118_auto_20200721_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-29 22:07:55', null=None),
        ),
    ]
