# Generated by Django 3.0.4 on 2020-07-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0119_auto_20200729_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-30 22:41:29', null=None),
        ),
    ]
