# Generated by Django 3.0.4 on 2020-07-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0119_merge_20200724_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-07-24 21:45:50', null=None),
        ),
    ]
