# Generated by Django 3.0.4 on 2020-08-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0123_auto_20200801_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-08-01 22:48:12', null=None),
        ),
    ]
