# Generated by Django 3.0.4 on 2020-08-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0124_auto_20200801_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-08-02 22:26:52', null=None),
        ),
    ]
