# Generated by Django 3.0.4 on 2020-08-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0125_auto_20200802_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-08-02 22:51:17', null=None),
        ),
    ]
