# Generated by Django 3.0.4 on 2020-08-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0126_auto_20200802_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-08-04 22:10:13', null=None),
        ),
    ]
