# Generated by Django 3.0.4 on 2020-08-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0128_auto_20200807_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-08-14 20:47:12', null=None),
        ),
    ]
