# Generated by Django 3.0.4 on 2020-08-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0129_auto_20200814_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-08-15 15:26:31', null=None),
        ),
    ]
