# Generated by Django 3.0.4 on 2020-09-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0130_auto_20200815_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-02 21:17:38', null=None),
        ),
    ]
