# Generated by Django 3.0.4 on 2020-09-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0131_auto_20200902_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-02 21:22:56', null=None),
        ),
    ]
