# Generated by Django 3.0.4 on 2020-09-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0133_auto_20200902_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-02 23:04:49', null=None),
        ),
    ]
