# Generated by Django 3.0.4 on 2020-09-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0135_auto_20200902_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-16 00:20:15', null=None),
        ),
    ]
