# Generated by Django 3.0.4 on 2020-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0136_auto_20200916_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-19 12:03:32', null=None),
        ),
    ]
