# Generated by Django 3.0.4 on 2020-09-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0138_auto_20200919_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-19 23:14:40', null=None),
        ),
    ]
