# Generated by Django 3.0.4 on 2020-09-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0139_auto_20200919_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-20 23:29:33', null=None),
        ),
    ]
