# Generated by Django 3.0.4 on 2020-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0140_auto_20200920_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-21 15:45:56', null=None),
        ),
    ]
