# Generated by Django 3.0.4 on 2020-09-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0141_auto_20200921_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-21 15:48:03', null=None),
        ),
    ]
