# Generated by Django 3.0.4 on 2020-09-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0143_auto_20200921_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-25 00:09:52', null=None),
        ),
    ]
