# Generated by Django 3.0.4 on 2020-09-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0144_auto_20200925_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-29 21:20:14', null=None),
        ),
    ]
