# Generated by Django 3.0.4 on 2020-09-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0145_auto_20200929_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-09-29 21:32:55', null=None),
        ),
    ]
