# Generated by Django 3.0.4 on 2020-10-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0150_auto_20201005_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-05 12:17:13', null=None),
        ),
    ]
