# Generated by Django 3.0.4 on 2020-10-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0151_auto_20201005_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-11 11:32:59', null=None),
        ),
    ]
