# Generated by Django 3.0.4 on 2020-10-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0153_auto_20201011_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-11 12:03:13', null=None),
        ),
    ]
