# Generated by Django 3.0.4 on 2020-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0154_auto_20201011_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-11 13:12:19', null=None),
        ),
    ]
