# Generated by Django 3.0.4 on 2020-10-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0155_auto_20201011_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-11 14:04:36', null=None),
        ),
    ]
