# Generated by Django 3.0.4 on 2020-10-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0156_auto_20201011_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-11 18:52:41', null=None),
        ),
    ]
