# Generated by Django 3.0.4 on 2020-10-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0157_auto_20201011_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-13 23:13:11', null=None),
        ),
    ]
