# Generated by Django 3.0.4 on 2020-10-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0159_auto_20201013_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-14 00:05:31', null=None),
        ),
    ]
