# Generated by Django 3.0.4 on 2020-10-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0161_auto_20201015_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-29 22:34:50', null=None),
        ),
    ]
