# Generated by Django 3.0.4 on 2020-10-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0162_auto_20201029_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-10-29 23:00:01', null=None),
        ),
    ]
