# Generated by Django 3.0.4 on 2020-11-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0165_auto_20201106_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2020-11-12 23:51:29', null=None),
        ),
    ]
