# Generated by Django 3.0.4 on 2021-02-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0166_auto_20201112_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePartida',
        ),
        migrations.DeleteModel(
            name='Materiales',
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=None, default='2021-02-05 21:29:00', null=None),
        ),
    ]
