# Generated by Django 3.0.4 on 2020-06-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentasM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idclie', models.IntegerField()),
                ('idprod', models.IntegerField()),
                ('cant', models.FloatField(default=1.0)),
                ('direcc', models.CharField(max_length=60)),
                ('costo', models.FloatField(default=0.0)),
            ],
        ),
    ]
