# Generated by Django 3.0.4 on 2020-07-18 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasm',
            name='direcc',
        ),
        migrations.AddField(
            model_name='ventasm',
            name='centr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventasm',
            name='direc',
            field=models.CharField(default='Retiro en tienda', max_length=100),
        ),
        migrations.AddField(
            model_name='ventasm',
            name='estado',
            field=models.CharField(default='POR ENTREGAR', max_length=12),
        ),
        migrations.AddField(
            model_name='ventasm',
            name='fhacd',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventasm',
            name='fhentr',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventasm',
            name='insm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventasm',
            name='mate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventasm',
            name='mobra',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventasm',
            name='obsrv',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ventasm',
            name='serv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventasm',
            name='utlds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ventasm',
            name='cant',
            field=models.FloatField(default=0.0),
        ),
    ]
