# Generated by Django 3.0.4 on 2020-07-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20200718_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventasm',
            old_name='mobra',
            new_name='pers',
        ),
    ]
