# Generated by Django 3.0.4 on 2020-07-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20200719_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayo', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('clie', models.IntegerField()),
                ('cant_s1', models.IntegerField()),
                ('tota_s1', models.IntegerField()),
                ('util_s1', models.FloatField()),
                ('insm_s1', models.FloatField()),
                ('mate_s1', models.FloatField()),
                ('pers_s1', models.FloatField()),
                ('serv_s1', models.FloatField()),
                ('cant_s2', models.IntegerField()),
                ('tota_s2', models.IntegerField()),
                ('util_s2', models.FloatField()),
                ('insm_s2', models.FloatField()),
                ('mate_s2', models.FloatField()),
                ('pers_s2', models.FloatField()),
                ('serv_s2', models.FloatField()),
                ('cant_s3', models.IntegerField()),
                ('tota_s3', models.IntegerField()),
                ('util_s3', models.FloatField()),
                ('insm_s3', models.FloatField()),
                ('mate_s3', models.FloatField()),
                ('pers_s3', models.FloatField()),
                ('serv_s3', models.FloatField()),
                ('cant_s4', models.IntegerField()),
                ('tota_s4', models.IntegerField()),
                ('util_s4', models.FloatField()),
                ('insm_s4', models.FloatField()),
                ('mate_s4', models.FloatField()),
                ('pers_s4', models.FloatField()),
                ('serv_s4', models.FloatField()),
            ],
        ),
    ]
