# Generated by Django 3.0.4 on 2020-07-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20200720_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumenm',
            name='ayo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumenm',
            name='insm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resumenm',
            name='mate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resumenm',
            name='mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumenm',
            name='ncli',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumenm',
            name='nped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumenm',
            name='pers',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resumenm',
            name='serv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resumenm',
            name='tota',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumenm',
            name='util',
            field=models.FloatField(default=0),
        ),
    ]
