# Generated by Django 3.0.4 on 2020-07-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20200720_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumenM',
        ),
    ]
