# Generated by Django 3.0.4 on 2020-07-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_delete_resumenm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayo', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('ncli', models.IntegerField(default=0)),
                ('nped', models.IntegerField(default=0)),
                ('tota', models.IntegerField(default=0)),
                ('util', models.FloatField(default=0)),
                ('insm', models.FloatField(default=0)),
                ('mate', models.FloatField(default=0)),
                ('pers', models.FloatField(default=0)),
                ('serv', models.FloatField(default=0)),
            ],
        ),
    ]
