# Generated by Django 3.0.4 on 2020-07-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20200721_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasm',
            name='estado',
            field=models.CharField(default='EN PROCESO', max_length=12),
        ),
    ]
