# Generated by Django 3.0.4 on 2020-07-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_auto_20200721_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasm',
            name='estado',
            field=models.CharField(default='EN_PRO', max_length=6),
        ),
    ]
