# Generated by Django 3.0.4 on 2020-09-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_auto_20200721_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasm',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
