# Generated by Django 3.0.4 on 2020-09-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_auto_20200925_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumenm',
            old_name='nped',
            new_name='npedc',
        ),
        migrations.AddField(
            model_name='resumenm',
            name='npedv',
            field=models.IntegerField(default=0),
        ),
    ]
