# Generated by Django 3.0.4 on 2020-11-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_auto_20201029_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumenm',
            name='npeds',
            field=models.IntegerField(default=0),
        ),
    ]
